//
//  IProject + Extension.swift
//  RaifMagic
//
//  Created by USOV Vasily on 18.03.2025.
//

extension IProject {
    /// Unique autogenerated identificator of project
    var id: String {
        "\(projectID.hashValue)-\(url.hashValue)"
    }
}
